### ISSUE TITLE
Ember-cli-deploy v1.0.0-beta.0, causes issues with this plugin

### ISSUE THREAD

**Issue by kriswill** [mwpastore/ember-cli-deploy-mysql#1]
After upgrading to ember-cli-deploy v1.0.0-beta.0, and running a configuration with this plugin activated, the following verbose error appears:
```
+- upload
|  |
|  +- mysql
|
+- didFail
TypeError: Cannot set property 'port' of undefined
TypeError: Cannot set property 'port' of undefined
    at Object.deployClient (/Users/kriswilliams/src/oss/ember-cli-deploy-mysql/index.js:45:29)
    at Class.readConfig (/Users/kriswilliams/src/oss/ember-cli-deploy-mysql/node_modules/ember-cli-deploy-plugin/index.js:63:30)
    at Class.upload (/Users/kriswilliams/src/oss/ember-cli-deploy-mysql/index.js:87:33)
    at Object.fn (/Users/kriswilliams/src/gliffy/ember-products/online-user-management/node_modules/ember-cli-deploy/lib/tasks/pipeline.js:93:21)
    at Pipeline._notifyPipelinePluginHookExecution (/Users/kriswilliams/src/gliffy/ember-products/online-user-management/node_modules/ember-cli-deploy/lib/models/pipeline.js:173:19)
    at tryCatch (/Users/kriswilliams/src/gliffy/ember-products/online-user-management/node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback (/Users/kriswilliams/src/gliffy/ember-products/online-user-management/node_modules/rsvp/dist/rsvp.js:554:13)
    at /Users/kriswilliams/src/gliffy/ember-products/online-user-management/node_modules/rsvp/dist/rsvp.js:629:16
    at flush (/Users/kriswilliams/src/gliffy/ember-products/online-user-management/node_modules/rsvp/dist/rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
|
Pipeline aborted
```

**Comment by mwpastore** [comment]
Hi @kriswill, I am deprecating ember-cli-deploy-mysql, and offering [ember-cli-deploy-sql](https://github.com/mwpastore/ember-cli-deploy-sql) as a replacement. It supports other databases in addition to MySQL/MariaDB, I actually know JavaScript now (I didn't when I wrote ember-cli-deploy-mysql), and there's a test suite with ~98% code coverage (ember-cli-deploy-mysql has no tests). 

I know it's tough to make time for busy work like this, but if you would please give it a try and let me know your thoughts, that would be great. There's a handy [migration guide](https://github.com/mwpastore/ember-cli-deploy-sql#migrating-from-ember-cli-deploy-mysql) that I tested on my own project. Thanks in advance!

**Comment by kriswill** [comment]
@mwpastore certainly!  I am currently wrapping up a busy sprint, and we're about to be working on deployment, so I'll see what I can do with ember-cli-deploy-sql and get back to you!
